# cmake/JSClosureCompile.cmake

message(STATUS "[JS Pipeline] Running Google Closure Compiler in ${PROCESSED_DIR}")

# 1. 使用 CMake 安全地获取所有要压缩的 JS 文件列表
file(GLOB_RECURSE JS_FILES RELATIVE "${PROCESSED_DIR}" "${PROCESSED_DIR}/components/*.js")

# 3. 动态构建传递给 Closure Compiler 的 --js 参数
set(CLOSURE_ARGS "")
foreach(JS_FILE ${JS_FILES})
    list(APPEND CLOSURE_ARGS "--js" "${PROCESSED_DIR}/${JS_FILE}")
endforeach()

if(USE_ADVANCED_MODE)
    message(STATUS "[JS Pipeline] JS Closure Compile Mode: ADVANCED_OPTIMIZATIONS")
    set(COMPILATION_LEVEL "ADVANCED_OPTIMIZATIONS")
else()
    message(STATUS "[JS Pipeline] JS Closure Compile Mode: SIMPLE_OPTIMIZATIONS")
    # 不改变属性名和代码逻辑
    set(COMPILATION_LEVEL "SIMPLE_OPTIMIZATIONS")
endif()

# 4. 运行 Closure Compiler
# ADVANCED_OPTIMIZATIONS
execute_process(
    COMMAND ${NODE_CMD} "${CLOSURE_COMPILER_SCRIPT}"
            --compilation_level ${COMPILATION_LEVEL}
            --dependency_mode PRUNE
            --entry_point "${PROCESSED_DIR}/components/main/main.js"
            ${CLOSURE_ARGS}
            --js_output_file "${PROCESSED_DIR}/main.min.js"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output_msg
    ERROR_VARIABLE error_msg
)

if(NOT result EQUAL 0)
    message(FATAL_ERROR "[JS Pipeline] Google Closure Compiler failed:\n${error_msg}")
endif()

# 检查文件是否成功生成且不为空
if(NOT EXISTS "${PROCESSED_DIR}/main.min.js")
    message(FATAL_ERROR "main.min.js was not generated by Closure Compiler!")
endif()

message(STATUS "[JS Pipeline] Successfully bundled JS into main.min.js")

# 5. 清理原有的零散 JS 文件 (避免它们混入 C++ 资源)
foreach(JS_FILE ${JS_FILES})
    file(REMOVE "${PROCESSED_DIR}/${JS_FILE}")
endforeach()

message(STATUS "[JS Pipeline] Cleaned up unbundled JS files.")